### ISSUE TITLE
Ledge 2.0 Roadmap 

### ISSUE THREAD

**Issue by phodal** [phodal/ledge#183]
2.0 的主要目标是：

 - 抽象出一个知识平台框架
 - 完善研发开发体系相关的知识

细化：

 - [x] DevOps 工具集优化
   - [x] 新的入口页面：优化现有的入口： https://openpracticelibrary.com/
   - [x] 操作步骤组件
 - [x] Ledge Framework
   - [x] JAMStack 架构框架
   - [x] 抽取 Ledge View
     - [x] 提取现有的 render 
   - [x] 创建 Ledge Engine
     - [x] 支持直接的 markdown loading
   - [x] 概念知识库
 - [x] 成熟度模型建设
   - [x] DevOps 成熟度模型
   - [x] CMMI 成熟度模型
 - [x] 研发体系知识
   - [x] DevOps 入门管理
   - [x] 智库建设
 - [x] 技能图谱
   - [x] 技能图谱框架 
   - [x] 成长模型 ？
 - [x] 重构
   - [x] `rating-radar-chart` 重写
   - [x] Ledge Render css 重构 
 - [x] 检查清单
  - [x] 记录历史
 - [x] 社区化
   - [x] 招聘栏目
 -  Serverless 后端
   -  招聘需求

**Comment by hylerrix** [comment]
对 Ledge Framework 有个新想法：支持中英批注的插件，如下图，点击中文后展示翻译前的中文。

![](https://user-images.githubusercontent.com/19285461/81177025-9db7d580-8fd8-11ea-818e-d6a860a5390f.png)

**Comment by kromalee** [comment]
请问一下 ledge2.0的知识平台相对于 vuepress,语雀有什么优势?也就是 `Why Ledge?`

**Comment by phodal** [comment]
@kromalee 可以看看 https://github.com/phodal/ascode.ink 里的文档代码化。代码化是未来的趋势

**Comment by kromalee** [comment]
我认为目前你提到的这些特性是可以用vuepress自定义主题和插件实现的,想请问下技术选型时考虑自己从头实现框架的决策依据是什么？

**Comment by phodal** [comment]
@kromalee 首先 vuePress 实现不了。其次是演进的过程中，发现现有的 markdown render 不满足需求，所以造的轮子。
